config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :shows
  resources :bands
  resources :categories
  root 'shows#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

# == Schema Information
# Schema version: 20150921192253
#
# Table name: admin_users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_admin_users_on_email                 (email) UNIQUE
#  index_admin_users_on_reset_password_token  (reset_password_token) UNIQUE
#

app/models/band.rb
class Band < ActiveRecord::Base
  belongs_to :category
  validates :name, presence: true
  validates :category, presence: true

  scope :index, -> { includes(:category).order(:name) }

  def to_s
    name
  end
end

# == Schema Information
#
# Table name: bands
#
#  id          :integer          not null, primary key
#  name        :string
#  category_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_bands_on_category_id  (category_id)
#

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_many :bands

  def to_s
   name
  end
end

# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/models/show.rb
class Show < ActiveRecord::Base
  belongs_to :band
  validates :band, :address, :start_at, :description, presence: true

  scope :upcoming, -> {
    includes(band: :category)
    .where('start_at >= ?', Time.current)
    .order(:start_at)
  }
end

# == Schema Information
# Schema version: 20150920120657
#
# Table name: shows
#
#  id          :integer          not null, primary key
#  band_id     :integer
#  address     :string
#  start_at    :datetime
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  image_url   :string
#
# Indexes
#
#  index_shows_on_band_id  (band_id)
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :set_band, only: [:show, :edit, :update, :destroy]

  # GET /bands
  # GET /bands.json
  def index
    @bands = Band.index
  end

  # GET /bands/1
  # GET /bands/1.json
  def show
  end

  # GET /bands/new
  def new
    @band = Band.new
  end

  # GET /bands/1/edit
  def edit
  end

  # POST /bands
  # POST /bands.json
  def create
    @band = Band.new(band_params)

    respond_to do |format|
      if @band.save
        format.html { redirect_to @band, notice: 'Band was successfully created.' }
        format.json { render :show, status: :created, location: @band }
      else
        format.html { render :new }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bands/1
  # PATCH/PUT /bands/1.json
  def update
    respond_to do |format|
      if @band.update(band_params)
        format.html { redirect_to @band, notice: 'Band was successfully updated.' }
        format.json { render :show, status: :ok, location: @band }
      else
        format.html { render :edit }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bands/1
  # DELETE /bands/1.json
  def destroy
    @band.destroy
    respond_to do |format|
      format.html { redirect_to bands_url, notice: 'Band was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_band
      @band = Band.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def band_params
      params.require(:band).permit(:name, :category_id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all.order(:name)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController

  before_action :set_show, only: [:show, :edit, :update, :destroy]

  # GET /shows
  # GET /shows.json
  def index
    @shows = Show.upcoming.decorate
  end

  # GET /shows/1
  # GET /shows/1.json
  def show
    @show = @show.decorate
  end

  # GET /shows/new
  def new
    @show = Show.new
  end

  # GET /shows/1/edit
  def edit
  end

  # POST /shows
  # POST /shows.json
  def create
    @show = Show.new(show_params)

    respond_to do |format|
      if @show.save
        format.html { redirect_to @show, notice: 'Show was successfully created.' }
        format.json { render :show, status: :created, location: @show }
      else
        format.html { render :new }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shows/1
  # PATCH/PUT /shows/1.json
  def update
    respond_to do |format|
      if @show.update(show_params)
        format.html { redirect_to @show, notice: 'Show was successfully updated.' }
        format.json { render :show, status: :ok, location: @show }
      else
        format.html { render :edit }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shows/1
  # DELETE /shows/1.json
  def destroy
    @show.destroy
    respond_to do |format|
      format.html { redirect_to shows_url, notice: 'Show was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_show
      @show = Show.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def show_params
      params.require(:show).permit(:band_id, :address, :start_at, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bands/_form.html.erb
<%= form_for(@band) do |f| %>
  <% if @band.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@band.errors.count, "error") %> prohibited this band from being saved:</h2>

      <ul>
      <% @band.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.text_field :category_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bands/edit.html.erb
<h1>Editing Band</h1>

<%= render 'form' %>

<%= link_to 'Show', @band %> |
<%= link_to 'Back', bands_path %>

app/views/bands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bands</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Name</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bands.each do |band| %>
      <tr>
        <td><img src="<%= Forgery::Image.url(200, 100, :music) %>"></td>
        <td><%= band.name %></td>
        <td><%= band.category %></td>
        <td><%= link_to 'Show', band %></td>
        <td><%= link_to 'Edit', edit_band_path(band) %></td>
        <td><%= link_to 'Destroy', band, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Band', new_band_path %>

app/views/bands/new.html.erb
<h1>New Band</h1>

<%= render 'form' %>

<%= link_to 'Back', bands_path %>

app/views/bands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @band.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @band.category %>
</p>

<%= link_to 'Edit', edit_band_path(@band) %> |
<%= link_to 'Back', bands_path %>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html<%== ' id="env-dev"' if Rails.env.development? %>>
<head>
  <title>Netshows</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="controller-<%= controller_name %> action-<%= action_name %>">

<div id="banner" data-vide-bg="http://cloud.profissional.ws/bgvideos/4.mp4" data-vide-options="posterType: none"></div>

<%= yield %>

<footer>
  <strong><%= Date.current.year %></strong>
  &copy; Marcos Neves
</footer>

</body>
</html>

app/views/shows/_form.html.erb
<%= form_for(@show) do |f| %>
  <% if @show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@show.errors.count, "error") %> prohibited this show from being saved:</h2>

      <ul>
      <% @show.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :band_id %><br>
    <%= f.text_field :band_id %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :start_at %><br>
    <%= f.datetime_select :start_at %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shows/edit.html.erb
<h1>Editing Show</h1>

<%= render 'form' %>

<%= link_to 'Show', @show %> |
<%= link_to 'Back', shows_path %>

app/views/shows/index.html.slim
header
  h1 = t'title'

main
  section
    - @shows.each do |show|
      article.wow.bounceInUp
        = link_to show do
          = image_tag show.image_url, width: 266, height: 150
        h3 = show.band_name
        h4 = l show.start_at, format: :short
        h5 = show.address
        h6 = show.category

app/views/shows/new.html.erb
<h1>New Show</h1>

<%= render 'form' %>

<%= link_to 'Back', shows_path %>

app/views/shows/show.html.slim
header
  h1 = @show.band_name
  .flipclock

  iframe src="https://www.google.com/maps/embed/v1/place?q=#{@show.address}&key=AIzaSyBRFo8Wi1mVk-Mhi4H8hPwzlx7u4C4mq2o" frameborder="0"

  p = @show.description.strip

javascript:
  $('.flipclock').FlipClock(#{@show.seconds_until_start}, {clockFace: 'DailyCounter', countdown: true})